server:
  port: 8051
spring:
  application:
    name: service-course-arrange
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: zhou0322
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis:
  type-aliases-package: cn.edu.zust.se.course-arrange.pojo
  configuration:
    map-underscore-to-camel-case: true